### ISSUE TITLE
Projekt pripravljen za zagovor

### ISSUE THREAD

**Issue by AccipitrisArti** [jaanos/APPR-2017-zagovori#12]
Projekt sem privedel do nekako zadovoljive oblike:
 AccipitrisArti/APPR-2017@993d112
Prosil bi za kakšen morebiten komentar, sicer pa za 'zeleno luč', da se s profesorjem dogovorim za ustni izpit.
Lp, Anže Marinko

**Comment by jaanos** [comment]
Projekt izgleda v redu, tako da bom dodal povezavo, ti se pa lahko s profesorjem dogovoriš za termin zagovora. Če boš še kaj spreminjal, mi javi, da posodobim povezavo.

Imam sicer še nekaj pripomb, bolj lepotne narave:

* Pri grafih z deleži izobrazbe si se zatipkal v oznaki osi y (**Ferkvenca** - zamenjani črki).
* Tabela z grupiranjem držav bi bila bolj pregledna, če bi jo uredil po skupini.
* V Shiny aplikaciji dobiš napako v zavihku *Primerjave spremenljivk* pri (privzeti) izbiri *Izberi funkcijo* - v `server.R` preverjaš za niz `Izberi metodo`. Shiny aplikacijo lahko morda tudi nekoliko povišaš (povečaj parameter `height` pri `shinyAppDir`), da bo v celoti vidna brez drsnika (vsaj v večini zavihkov).

**Comment by AccipitrisArti** [comment]
Prosil bi, da nadomestite staro verzijo z novejšo.
Verzija upoštevajoč Vaše nasvete:
 AccipitrisArti/APPR-2017@9d30745
Hvala.
Lp,   Anže

**Comment by jaanos** [comment]
V redu, sem posodobil.
