### ISSUE TITLE
Predstavitev

### ISSUE THREAD

**Issue by AccipitrisArti** [jaanos/APPR-2017-zagovori#2]
AccipitrisArti/APPR-2017@881038d

**Comment by jaanos** [comment]
Poročila mi ne prevede - če v `vizualizacija.r` v funkciji `zemljevid.evrope` v prvi vrstici nadomestiš stolpec `NUTS_ID` (ki ni faktor) s stolpcem `drzava`, pa deluje.

Svetoval bi še, da pri stolpčnem grafu prišteješ
```R
theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```
Tako se bodo imena držav izpisala navpično.
